### PR TITLE
Handle broken pipe signal

### PR DESCRIPTION
**Pull request by pavlin99th**

### CODE REVIEW

**Comment by kmyk** [comment]
You say about this `BrokenPipeError`, right?

```
$ python3 setup.py test
...
Traceback (most recent call last):
  File "/usr/local/bin/mt19937predict", line 24, in <module>
    main()
  File "/usr/local/bin/mt19937predict", line 21, in main
    print(predictor.genrand_int32())
BrokenPipeError: [Errno 32] Broken pipe
...
```

Yes, this error is safe but ugly.
However, I want to simply catch the exception with `except` instead of `signal`, since signals seems too environment-dependent for this script.
I'll merge this pull request in such a way if my understanding is correct. Thank you!

**Comment by pavlin99th** [comment]
How about this?
```
with contextlib.suppress(BrokenPipeError):
    while True:
        print(predictor.genrand_int32())
```

**Comment by kmyk** [comment]
Wow, I didn't know the convenient function.
I want to merge using this.

**Comment by kmyk** [comment]
I've uploaded this modification to the PyPI server. You can update this with `pip3 install -U mersenne-twister-predictor` now.
Thank you for nice pull request!

**Pull request merged**
